name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
        - name: macOS
          os: macos-latest
        - name: Android32
          os: ubuntu-latest
          target: Android32
        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@v2
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          target: ${{ matrix.config.target }}
          cli: v3.2.0

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geode-build-${{ matrix.config.name }}
          path: ${{ workspace }}/*.geode
